send_command('bind !i send @all /mount Ixion')
send_command('bind !l send @all /lightshot zattano')
send_command('bind !d send @all /darkshot <bt>')
send_command('bind !t send tigertale /dia2 <bt>')
send_command('bind !b send @all /Bolters roll')
send_command('bind !c send @all /Chaos Roll')
send_command('bind !v send @all /Samurai Roll')
send_command('bind !k send @all /lightshot <bt>')
send_command('bind !h send tigertale /assist Zattano; wait 0.5; send tigertale /Hordelullaby ii <t>; wait 0.8; send tigertale /lockon')
send_command('bind !j send @all /assist Zattano; send @all /Savageblade <t>')
send_command('bind !x send @all /doubleup>')
send_command('bind !z send @all /Crooked Cards>')
send_command('bind !p send @all gs equip sets.phalanx')